# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
    component: otel-collector-config
  namespace: otel-collector-log-demo

data:
  otel-collector-config: |
    receivers:
      filelog:
        include:
          - /var/log/otel-json.log
        start_at: beginning
        id: json-log
        include_file_path: true
        operators:
          - type: json_parser
            id: parser-app-json
            timestamp:
              parse_from: attributes.time
              layout_type: gotime
              layout: '2006-01-02T15:04:05.999999999Z07:00'

    processors:
      batch:

    exporters:
      googlecloud:
        log:
          default_log_name: opentelemetry.io/collector-exported-log

    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch]
          exporters: [googlecloud]

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    component: otel-collector
  namespace: otel-collector-log-demo
spec:
  selector:
    app: otel-collector
  ports:
    - port: 4317
      name: otlp-grpc
      protocol: TCP
      targetPort: 4317

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    component: otel-collector
  namespace: otel-collector-log-demo
spec:
  selector:
    matchLabels:
      app: otel-collector
      component: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
        component: otel-collector
    spec:
      containers:
        - name: log-app
          image: app
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: json-log-vol
              mountPath: /var/log
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.92.0-amd64
          command:
            - "/otelcol-contrib"
            - "--config=/conf/otel-collector-config.yaml"
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
              readOnly: true
            - name: json-log-vol
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-config
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
        - name: json-log-vol
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: log-app-external
  namespace: otel-collector-log-demo
  labels:
    app: otel-collector
spec:
  type: LoadBalancer
  selector:
    app: otel-collector
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
