-- Reverse engineered schema for tenkai-db/tenkai
-- Optimized for PostgreSQL 18
-- Derived from internal/db/db.go

-- Standard Extensions (ensure JSONB and other features are available)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS experiments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    timestamp TIMESTAMP WITH TIME ZONE,
    config_path TEXT,
    report_path TEXT,
    results_path TEXT,
    status TEXT,
    reps INTEGER,
    concurrent INTEGER,
    total_jobs INTEGER DEFAULT 0,
    error_message TEXT,
    pid INTEGER,
    description TEXT,
    duration BIGINT DEFAULT 0,
    config_content TEXT,
    report_content TEXT,
    execution_control TEXT,
    experiment_control TEXT,
    ai_analysis TEXT,
    is_locked BOOLEAN DEFAULT FALSE,
    annotations TEXT
);

CREATE TABLE IF NOT EXISTS run_results (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_id INTEGER REFERENCES experiments(id) ON DELETE CASCADE,
    alternative TEXT,
    scenario TEXT,
    repetition INTEGER,
    duration BIGINT,
    error TEXT,
    tests_passed INTEGER,
    tests_failed INTEGER,
    lint_issues INTEGER,
    raw_json JSONB,
    total_tokens INTEGER DEFAULT 0,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    cached_tokens INTEGER DEFAULT 0,
    tool_calls_count INTEGER DEFAULT 0,
    failed_tool_calls INTEGER DEFAULT 0,
    loop_detected BOOLEAN DEFAULT FALSE,
    stdout TEXT,
    stderr TEXT,
    is_success BOOLEAN DEFAULT FALSE,
    validation_report TEXT,
    status TEXT,
    reason TEXT,
    model TEXT,
    session_id TEXT,
    model_duration INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER REFERENCES run_results(id) ON DELETE CASCADE,
    type TEXT,
    timestamp TIMESTAMP WITH TIME ZONE,
    payload JSONB
);

CREATE TABLE IF NOT EXISTS run_files (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER REFERENCES run_results(id) ON DELETE CASCADE,
    path TEXT,
    content TEXT,
    is_generated BOOLEAN
);

CREATE TABLE IF NOT EXISTS test_results (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER REFERENCES run_results(id) ON DELETE CASCADE,
    name TEXT,
    status TEXT,
    duration_ns BIGINT,
    output TEXT
);

CREATE TABLE IF NOT EXISTS lint_results (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER REFERENCES run_results(id) ON DELETE CASCADE,
    file TEXT,
    line INTEGER,
    col INTEGER,
    message TEXT,
    severity TEXT,
    rule_id TEXT
);

CREATE TABLE IF NOT EXISTS config_blocks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    content TEXT NOT NULL,
    UNIQUE(name, type)
);

-- Indices
-- Note: PG 18 supports concurrent index creation more robustly, but for initial schema standard is fine.
CREATE UNIQUE INDEX IF NOT EXISTS idx_experiments_name_ts ON experiments(name, timestamp);
CREATE UNIQUE INDEX IF NOT EXISTS idx_run_results_unique_run ON run_results(experiment_id, alternative, scenario, repetition);
CREATE INDEX IF NOT EXISTS idx_run_events_run_id ON run_events(run_id);
CREATE INDEX IF NOT EXISTS idx_run_events_type ON run_events(type);

-- Views
-- PostgreSQL 18 optimized view definitions
CREATE OR REPLACE VIEW tool_usage AS 
SELECT 
    id, 
    run_id, 
    payload ->> 'name' as name,
    payload -> 'args' as args,
    payload ->> 'status' as status,
    payload ->> 'output' as output,
    payload ->> 'error' as error,
    (payload ->> 'duration')::bigint as duration,
    timestamp
FROM run_events 
WHERE type = 'tool';

CREATE OR REPLACE VIEW messages AS 
SELECT 
    id, 
    run_id, 
    payload ->> 'role' as role,
    payload ->> 'content' as content,
    timestamp
FROM run_events 
WHERE type = 'message';