#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Exports the environment that both agent projects need.
#
# Source this, do not execute it, so the variables land in your own shell:
#
#     source ./setenv.sh
#
# PROJECT_ID and REGION come from the lab's Qwiklabs variables, which you
# exported in the "Before You Begin" task. Everything else is derived from them.
#
# This script deliberately writes no files. Each agent project is generated by
# `agents-cli create`, and its .env belongs to that tool.

# Both values are recovered the same way: keep what is already exported, and
# only fall back when it is missing.
#
# First fallback: the file lab-setup.sh saved in your home directory, which
# Cloud Shell keeps across sessions. This is what survives a lost session.
LAB_ENV_FILE="$HOME/.env"
if [ -f "$LAB_ENV_FILE" ]; then
  PROJECT_ID="${PROJECT_ID:-$(sed -n 's/^PROJECT_ID="\(.*\)"$/\1/p' "$LAB_ENV_FILE")}"
  REGION="${REGION:-$(sed -n 's/^REGION="\(.*\)"$/\1/p' "$LAB_ENV_FILE")}"
fi

# Second fallback: the gcloud configuration, which lab-setup.sh already pinned
# to the lab's project and region.
PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project 2>/dev/null)}"
REGION="${REGION:-$(gcloud config get-value run/region 2>/dev/null)}"

if [ -z "$PROJECT_ID" ] || [ -z "$REGION" ]; then
  echo "⚠️   PROJECT_ID or REGION is not set, and could not be read from gcloud."
  echo "👉  Export them using the values in the lab panel, then source this again:"
  echo "       export PROJECT_ID=\"your-qwiklabs-project-id\""
  echo "       export REGION=\"your-lab-region\""
  # `return` when sourced, `exit` when executed.
  return 1 2>/dev/null || exit 1
fi

# Ensure user-local binaries (uv, and the agents-cli it installs) take precedence
# over the older agents-cli that Cloud Shell pre-installs system-wide.
export PATH="$HOME/.local/bin:$PATH"
hash -r 2>/dev/null || true

export PROJECT_ID
export REGION

export GOOGLE_CLOUD_PROJECT="$PROJECT_ID"
export GOOGLE_CLOUD_REGION="$REGION"
export GOOGLE_CLOUD_LOCATION="global"
export GOOGLE_GENAI_USE_VERTEXAI="true"

gcloud config set project "$PROJECT_ID"

# Where the coordinator looks for the Visual Director. Left as the local address
# for the build-and-test tasks; the deploy task replaces it with a Cloud Run URL.
export VISUAL_DIRECTOR_URL="${VISUAL_DIRECTOR_URL:-http://localhost:8801}"

echo "  🎉  🦄  Environment configured:"
echo "  GOOGLE_CLOUD_PROJECT:  $GOOGLE_CLOUD_PROJECT"
echo "  GOOGLE_CLOUD_REGION:   $GOOGLE_CLOUD_REGION"
echo "  GOOGLE_CLOUD_LOCATION: $GOOGLE_CLOUD_LOCATION"
echo "  VISUAL_DIRECTOR_URL:   $VISUAL_DIRECTOR_URL"
