// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB08eGD_fx5DZnITalKhOH9LLtJKGMDHqw',
    appId: '1:914235183282:web:d6d8dcff800752282879ab',
    messagingSenderId: '914235183282',
    projectId: 'yenkhanh-flutter',
    authDomain: 'yenkhanh-flutter.firebaseapp.com',
    storageBucket: 'yenkhanh-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXcQK_BO2Sk98-uReCcsuXyDFVOywkiD4',
    appId: '1:914235183282:android:e2045ba5533634ed2879ab',
    messagingSenderId: '914235183282',
    projectId: 'yenkhanh-flutter',
    storageBucket: 'yenkhanh-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvZ0_4-17-2-5ndic25SrBjZ0Boh4mOME',
    appId: '1:914235183282:ios:9b9fe4ac138d7d622879ab',
    messagingSenderId: '914235183282',
    projectId: 'yenkhanh-flutter',
    storageBucket: 'yenkhanh-flutter.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );
}
