
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/root/.ssh/publickey"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
data:
  TRANSACTIONS_API_ADDR: "ledgerwriter:8080"
  BALANCES_API_ADDR: "balancereader:8080"
  HISTORY_API_ADDR: "transactionhistory:8080"
  CONTACTS_API_ADDR: "contacts:8080"
  USERSERVICE_API_ADDR: "userservice:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "testuser"
  # All demo user accounts are hardcoded to use the login password 'bankofanthos'
  DEMO_LOGIN_PASSWORD: "bankofanthos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-db-config
  labels:
    app: accounts-db
data:
  # Updated to use CloudSQL Proxy
  ACCOUNTS_DB_URI: postgresql://postgres:Chiapet22!@127.0.0.1:5432/accounts-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Chiapet22!
  # Updated to use CloudSQL Proxy
  SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/ledger-db
  SPRING_DATASOURCE_USERNAME: postgres # should match POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: Chiapet22! # should match POSTGRES_PASSWORD