apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - balance-reader.yaml 
  - config.yaml 
  - contacts.yaml
  - frontend.yaml 
  - jwt-secret.yaml
  - ledger-writer.yaml
  - loadgenerator.yaml
  - transaction-history.yaml 
  - userservice.yaml
