---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cymbal-store-embeddings
spec:
  selector:
    matchLabels:
      app: cymbal-store
  template:
    metadata:
      labels:
        app: cymbal-store
    spec:
      containers:
      - name: cymbal-store
        # Replace <PROJECT_ID> and <REGION> with your project ID and region.
        image: us-central1-docker.pkg.dev/$PROJECT_ID/cymbal-store-embeddings/cymbal_store:latest
        imagePullPolicy: Always
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: INSTANCE_HOST
          value: "34.118.226.5"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cymbal-store-embeddings-secret
              key: username
        - name: DB_PASS
          valueFrom:
           secretKeyRef:
              name: cymbal-store-embeddings-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cymbal-store-embeddings-secret
              key: database
---
apiVersion: v1
kind: Service
metadata:
  name: cymbal-store-service
spec:
  type: ClusterIP
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: cymbal-store
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
