apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: kueue-lws-simple-subslicing
  namespace: llm-d-pd-disaggregation
  annotations:
    leaderworkerset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-tpu-slice
  labels:
    kueue.x-k8s.io/queue-name: lq
    kueue.x-k8s.io/priority-class: low-priority-1000
spec:
  replicas: 16
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        annotations:
          cloud.google.com/gke-tpu-slice-topology: "2x2x2"
      spec:
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
#          cloud.google.com/gke-tpu-partition-2x2x2-state: "HEALTHY"
        tolerations:
        - effect: NoSchedule   
          key: google.com/tpu
          operator: Exists
        containers:
          - name: simple-leader
            image: python:3.12
            imagePullPolicy: IfNotPresent
            env:
              - name: TPU_MULTIHOST_BACKEND
                value: ray
              - name: TPU_NODE_ID
                value: $(LWS_WORKER_INDEX)
              - name: RAY_RESERVE_CPU_FOR_RAYLET
                value: "1"
              - name: RAY_heartbeat_timeout_milliseconds
                value: "300000"
              - name: RAY_initial_reconstruction_timeout_milliseconds
                value: "300000"
              - name: RAY_external_storage_heartbeat_timeout_ms
                value: "60000"
              - name: RAY_grpc_server_thread_pool_size
                value: "100"
              - name: RAY_max_pending_lease_requests_per_scheduling_category
                value: "1000"
              - name: RAY_rpc_server_listen_quiet_period_ms
                value: "3600000"
              - name: RAY_gcs_server_request_timeout_seconds
                value: "3600"
            command:
            - bash
            - -c
            - |
              set -ex
              
              pip install -U --pre jax jaxlib libtpu requests -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/ -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
              pip list
              python -c 'import jax; print("Total TPU devices (cores):", jax.device_count())' &&
              sleep infinity
            resources:
              limits:
                google.com/tpu: "4"
              requests:
                google.com/tpu: "4"
    workerTemplate:
      metadata:
        annotations:
          cloud.google.com/gke-tpu-slice-topology: "2x2x2"
      spec:
        nodeSelector:
          cloud.google.com/gke-tpu-accelerator: tpu7x
#          cloud.google.com/gke-tpu-partition-2x2x2-state: "HEALTHY"
        tolerations:
        - effect: NoSchedule   
          key: google.com/tpu
          operator: Exists
        containers:
          - name: simple-worker
            image: python:3.12
            imagePullPolicy: IfNotPresent
            command:
            - bash
            - -c
            - |
              set -ex
              
              pip install -U --pre jax jaxlib libtpu requests -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/ -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
              pip list
              python -c 'import jax; print("Total TPU devices (cores):", jax.device_count())' &&
              sleep infinity
            resources:
              limits:
                google.com/tpu: "4"
              requests:
                google.com/tpu: "4"
            env:
              - name: TPU_MULTIHOST_BACKEND
                value: ray
              - name: TPU_NODE_ID
                value: $(LWS_WORKER_INDEX)
              - name: RAY_RESERVE_CPU_FOR_RAYLET
                value: "1"
              - name: RAY_heartbeat_timeout_milliseconds
                value: "300000"
              - name: RAY_initial_reconstruction_timeout_milliseconds
                value: "300000"
              - name: RAY_external_storage_heartbeat_timeout_ms
                value: "60000"
              - name: RAY_grpc_server_thread_pool_size
                value: "100"
              - name: RAY_max_pending_lease_requests_per_scheduling_category
                value: "1000"
              - name: RAY_rpc_server_listen_quiet_period_ms
                value: "3600000"
              - name: RAY_gcs_server_request_timeout_seconds
                value: "3600"
