# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x0c\x63ode_samples\"\xab\x01\n\x10TransactionEvent\x12\x16\n\x0etransaction_id\x18\x01 \x02(\t\x12\x18\n\x10\x63\x61rd_number_hash\x18\x02 \x02(\t\x12\x0e\n\x06\x61mount\x18\x03 \x02(\x01\x12\x13\n\x0bmerchant_id\x18\x04 \x02(\t\x12\x11\n\ttimestamp\x18\x05 \x02(\t\x12\x18\n\x10\x66raud_risk_score\x18\x06 \x02(\x01\x12\x13\n\x0b\x61lert_level\x18\x07 \x01(\t\"\xa8\x01\n\x13InventoryAdjustment\x12\x15\n\radjustment_id\x18\x01 \x02(\t\x12\x14\n\x0cwarehouse_id\x18\x02 \x02(\t\x12\x10\n\x08item_sku\x18\x03 \x02(\t\x12\x18\n\x10quantity_changed\x18\x04 \x02(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x02(\t\x12\x11\n\ttimestamp\x18\x06 \x02(\t\x12\x13\n\x0boperator_id\x18\x07 \x01(\t\"\xb8\x01\n\x10VehicleTelemetry\x12\x14\n\x0ctelemetry_id\x18\x01 \x02(\t\x12\x13\n\x0bvehicle_vin\x18\x02 \x02(\t\x12\x11\n\tspeed_mph\x18\x03 \x02(\x01\x12\x10\n\x08latitude\x18\x04 \x02(\x01\x12\x11\n\tlongitude\x18\x05 \x02(\x01\x12\x11\n\ttimestamp\x18\x06 \x02(\t\x12\x1d\n\x15safety_trigger_active\x18\x07 \x02(\x08\x12\x0f\n\x07G_force\x18\x08 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONEVENT']._serialized_start=31
  _globals['_TRANSACTIONEVENT']._serialized_end=202
  _globals['_INVENTORYADJUSTMENT']._serialized_start=205
  _globals['_INVENTORYADJUSTMENT']._serialized_end=373
  _globals['_VEHICLETELEMETRY']._serialized_start=376
  _globals['_VEHICLETELEMETRY']._serialized_end=560
# @@protoc_insertion_point(module_scope)
