  name: 'CymbalBank - Build and deploy to GKE'

  on:
    push:
      branches:
        - "next25-aws-gcp-migration"
  
  defaults: 
    run:
      working-directory: './containers/aws-gcp-migration'
  
  env:
    PROJECT_ID: 'next25migration'  
    REGION: 'us-central1'
    GKE_CLUSTER: 'megan-test-cluster' 
    REPOSITORY: 'megan-test-ar'  
  
  jobs:
    build-and-deploy-gke:
      runs-on: ubuntu-latest
  
      permissions:
        id-token: write # Required for workload identity federation
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v2
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
  
        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
  
        - name: 'Docker Auth'
          run: |-
            gcloud --quiet auth configure-docker ${REGION}-docker.pkg.dev
        
        - name: 'Install GKE auth plugin and kustomize' 
          run: |-
            gcloud components install gke-gcloud-auth-plugin
            gcloud components install --quiet kustomize

        - name: 'Auth to GKE cluster' 
          run: |-
            gcloud container clusters get-credentials $GKE_CLUSTER --region $REGION --project $PROJECT_ID
     
        - name: 'CONTACTS - build and push'
          run: |- 
            IMAGE="contacts" 
            echo "\npwd" 
            pwd 

            echo "\nls"
            ls
            cd gcp/src/accounts/contacts 

            DOCKER_TAG="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"
  
            echo "🐳 Build and push container image: ${DOCKER_TAG}"

            docker build \
              --tag "${DOCKER_TAG}" \
              --build-arg GITHUB_SHA="${GITHUB_SHA}" \
              --build-arg GITHUB_REF="${GITHUB_REF}" \
              .
  
            docker push "${DOCKER_TAG}"
            cd $GITHUB_WORKSPACE
            pwd 
            ls 
            cd containers/aws-gcp-migration/gcp/kubernetes
            kustomize edit set image contacts=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}
            cat contacts.yaml
  
        - name: 'Deploy CymbalBank to GKE'
          run: |-
            echo "\npwd" 
            pwd 

            echo "\nls"
            ls
            cd gcp/kubernetes
            kubectl apply -k .
